# The MIT License (MIT).
#
# Copyright (c) 2018-2025 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
# OR OTHER DEALINGS IN THE SOFTWARE.
---
test-free-files:
  - .*__init__.py
  - .*app_types.*
  - src/db/connection.py
  - src/exceptions.*
  - src/tests/.*
  - .*fk_.*\.py
  # protocols:
  - src/srv/prayers/prayers_info.py
  - src/srv/prayers/new_prayers.py
  - src/srv/ayats/text_search_query.py
  - src/integrations/tg/keyboard.py
  - src/integrations/tg/sendable.py
  - src/integrations/tg/tg_answers/tg_answer.py
  - src/integrations/tg/udpates_url_interface.py
  - src/integrations/tg/updates_iterator.py
  - src/services/debug_param.py
  - src/srv/ayats/ayat_identifier.py
  - src/srv/ayats/favorite_ayat_status.py
  - src/srv/ayats/neighbor_ayats.py
  - src/srv/ayats/neighbor_ayats_buttons.py
  - src/srv/ayats/search_query.py
  - src/srv/events/event_hook.py
  - src/srv/events/sink.py
  - src/srv/files/tg_file.py
  - src/srv/podcasts/changed_podcast_reaction.py
  - src/srv/podcasts/podcast_reaction.py
  - src/srv/prayers/city.py  # Почему у этого интерфейса есть тест
  - src/srv/prayers/exist_user_prayers.py
  - src/srv/prayers/new_prayers_at_user.py
  - src/srv/prayers/prayer_date.py  # Почему у этого интерфейса есть тест?
  - src/srv/prayers/prayers_stts.py
  - src/srv/prayers/updated_user_city.py
  - src/srv/prayers/user_prayer_stts.py
  # Почему-то существует 2 одинаковых протокола
  - src/srv/start/new_user.py
  - src/srv/users/new_user.py
  - src/srv/users/updated_users_status.py
  - src/srv/users/user.py
  - src/srv/users/user_state.py
  # TODO
  - src/handlers/full_start_answer.py
  - src/handlers/pagination_per_day_prayer_answer.py
  - src/handlers/podcast_message_text_not_exists_safe_answer.py
  - src/handlers/prayers_statistic.py
  - src/handlers/search_ayat_by_keyword_answer.py
  - src/handlers/search_ayat_by_numbers_answer.py
  - src/handlers/skipped_prayers_keyboard.py
  - src/integrations/tg/app_with_get_me.py
  - src/integrations/tg/bulk_sendable_answer.py
  - src/integrations/tg/cached_tg_update.py
  - src/integrations/tg/database_connected_app.py
  - src/integrations/tg/exceptions/update_parse_exceptions.py
  - src/integrations/tg/inline_query_id.py
  - src/integrations/tg/polling_app.py
  - src/integrations/tg/polling_updates.py
  - src/integrations/tg/sendable_answer.py
  - src/integrations/tg/tg_answers/delete_message_answer.py
  - src/integrations/tg/tg_answers/edit_message_text.py
  - src/integrations/tg/tg_answers/link_preview_options.py
  - src/integrations/tg/tg_answers/message_answer_to_sender.py
  - src/integrations/tg/tg_answers/skipable_answer.py
  - src/integrations/tg/tg_answers/text_answer.py
  - src/integrations/tg/tg_message_coordinates.py
  - src/integrations/tg/typing_action.py
  - src/integrations/tg/udpates_with_offset_url.py
  - src/integrations/tg/update.py
  - src/integrations/tg/updates_timeout.py
  - src/integrations/tg/updates_url.py
  - src/integrations/tg/upddates_long_pollinig_url.py
  - src/integrations/tg/user_not_subscribed_safe_sendable.py
  - src/main.py
  - src/quranbot_answer.py
  - src/scheduler_entry.py
  - src/services/answers/change_state_answer.py
  - src/services/answers/default_keyboard.py
  - src/services/answers/resized_keyboard.py
  - src/services/answers/safe_fork.py
  - src/services/append_debug_info_answer.py
  - src/services/chat_id_debug_param.py
  - src/services/cli_app.py
  - src/services/command_cli_app.py
  - src/services/commit_hash_debug_param.py
  - src/services/debug_answer.py
  - src/services/err_redirect_json_path.py
  - src/services/fork_cli_app.py
  - src/services/help_answer.py
  - src/services/json_path.py
  - src/services/json_path_value.py
  - src/services/match_many_json_path.py
  - src/services/reset_state_answer.py
  - src/services/state_answer.py
  - src/services/switch_inline_query_answer.py
  - src/services/time_debug_param.py
  - src/services/update_id_debug_param.py
  - src/settings.py
  - src/srv/admin_messages/admin_message.py
  - src/srv/admin_messages/pg_admin_message.py
  - src/srv/ayats/ayat.py
  - src/srv/ayats/ayat_answer.py
  - src/srv/ayats/ayat_answer_keyboard.py
  - src/srv/ayats/ayat_by_id_answer.py
  - src/srv/ayats/ayat_by_id_message_answer.py
  - src/srv/ayats/ayat_by_sura_ayat_num_answer.py
  - src/srv/ayats/ayat_callback_template_enum.py
  - src/srv/ayats/ayat_favorite_keyboard_button.py
  - src/srv/ayats/ayat_favorite_status.py
  - src/srv/ayats/ayat_id_by_public_id.py
  - src/srv/ayats/ayat_id_by_sura_ayat_num.py
  - src/srv/ayats/ayat_link.py
  - src/srv/ayats/ayats_by_text_query.py
  - src/srv/ayats/cached_text_search_query.py
  - src/srv/ayats/favorite_ayat_answer.py
  - src/srv/ayats/favorite_ayat_page.py
  - src/srv/ayats/favorite_ayats.py
  - src/srv/ayats/favorites/ayat_is_favor.py
  - src/srv/ayats/neighbor_ayat_keyboard.py
  - src/srv/ayats/neighbor_ayats_btns.py
  - src/srv/ayats/nums_search_query.py
  - src/srv/ayats/pg_ayat_identifier.py
  - src/srv/ayats/search_ayat_by_text.py
  - src/srv/events/ayat_changed_event.py
  - src/srv/events/event_fork.py
  - src/srv/events/event_hook_app.py
  - src/srv/events/prayer_created_event.py
  - src/srv/events/rabbitmq_sink.py
  - src/srv/events/rbmq_event_hook.py
  - src/srv/events/recieved_event.py
  - src/srv/files/tg_file_id_not_filled_safe_answer.py
  - src/srv/message_not_found_safe_answer.py
  - src/srv/podcasts/markupped_podcast_answer.py
  - src/srv/podcasts/pg_changed_podcast_reaction.py
  - src/srv/podcasts/podcast_answer.py
  - src/srv/podcasts/podcast_keyboard.py
  - src/srv/podcasts/random_podcast_answer.py
  - src/srv/prayers/city_not_supported_answer.py
  - src/srv/prayers/date_from_user_prayer_id.py
  - src/srv/prayers/exist_user_prayers_dict.py
  - src/srv/prayers/pg_city.py
  - src/srv/prayers/pg_city_change_safe_user_prayers.py
  - src/srv/prayers/pg_exist_user_prayers.py
  - src/srv/prayers/pg_new_prayers_at_user.py
  - src/srv/prayers/pg_updated_user_city.py
  - src/srv/prayers/prayer_names.py
  - src/srv/prayers/prayers_expired_answer.py
  - src/srv/prayers/prayers_mark_as_date.py
  - src/srv/prayers/prayers_request_date.py
  - src/srv/prayers/pg_prayers_info.py
  - src/srv/prayers/user_prayer_status.py
  - src/srv/prayers/user_without_city_safe_answer.py
  - src/srv/start/new_tg_user.py
  - src/srv/start/referrer_chat_id.py
  - src/srv/start/referrer_id_or_none.py
  - src/srv/start/start_answer.py
  - src/srv/start/user_already_active.py
  - src/srv/start/user_already_exists.py
  - src/srv/users/cached_user_state.py
  - src/srv/users/chat_id_by_legacy_id.py
  - src/srv/users/pg_active_users.py
  - src/srv/users/pg_new_user.py
  - src/srv/users/pg_new_user_with_event.py
  - src/srv/users/pg_updated_users_status.py
  - src/srv/users/pg_users.py
  - src/srv/users/pg_valid_chat_id.py
  - src/srv/users/redis_user_state.py
  - src/srv/users/updated_users_status_event.py
  - src/srv/prayers/pg_saved_prayers_info.py
  - src/srv/users/user_step.py
  - src/srv/users/valid_chat_id.py
  # TODO #1438:30min Написать тесты на src/srv/prayers/prayers_text.py
  - src/srv/prayers/prayers_text.py
  # TODO #1438:30min Написать тесты на src/handlers/nt_prayer_time_answer.py
  - src/handlers/nt_prayer_time_answer.py
  # TODO #1675:30min Написать тесты на src/handlers/hg_prayer_time_answer.py
  - src/handlers/hg_prayer_time_answer.py
  # TODO #1438:30min Написать тесты на src/integrations/tg/tg_answers/tg_chat_id_regex_answer.py
  - src/integrations/tg/tg_answers/tg_chat_id_regex_answer.py
  # TODO #1428:30min Написать тесты на NtPrayersUrl
  - src/srv/prayers/nt_prayers_url.py
  # TODO #1676:30min Написать тесты на HgPrayersUrl
  - src/srv/prayers/hg_prayers_url.py
test-helpers:
  - .*conftest.py
  - .*__init__.py
  # TODO
  - src/tests/unit/services/test_append_update_id_answer.py
  - src/tests/unit/srv/prayers/test_podcasts_reaction_change_answer.py
  - src/tests/unit/srv/prayers/test_ramadan_prayer_text_unit.py
  - src/tests/unit/test_reset_state_answer.py
  - src/tests/unit/test_rounded_float.py
  - src/tests/unit/test_user_state.py
  - src/tests/it/handlers/test_pagination_per_day_answer.py
  - src/tests/it/srv/ayats/test_ayat_id_by_sura_ayat.py
  - src/tests/it/srv/events/test_create_prayer.py
  - src/tests/it/srv/prayers/test_prayers.py
  - src/tests/it/srv/prayers/test_update_user_city.py
  - src/tests/it/test_start.py
