# SPDX-FileCopyrightText: Copyright (c) 2018-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT

FROM python:3.14.2-slim
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV EC_VERSION="v3.1.2"
ENV PATH="/root/.local/bin:$PATH"
WORKDIR /app
RUN pip install poetry==2.0.1
RUN apt-get update && apt-get install gcc curl postgresql-client git redis -y
RUN curl -O -L -C - https://github.com/editorconfig-checker/editorconfig-checker/releases/download/$EC_VERSION/ec-linux-amd64.tar.gz && \
    tar xzf ec-linux-amd64.tar.gz -C /tmp && \
    mkdir -p /root/.local/bin && \
    mv /tmp/bin/ec-linux-amd64 /root/.local/bin/ec
RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /bin
COPY poetry.lock pyproject.toml /app/
# RUN poetry install
COPY src/ /app/src
COPY Taskfile.yml /app
