# SPDX-FileCopyrightText: Copyright (c) 2018-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT
---
version: 3

tasks:

  compose-setup:
    cmds:
      - docker compose build

  compose-run:
    cmds:
      - docker compose up -d

  compose-test:
    cmds:
      - docker compose run --rm qbot task tests

  compose-bash:
    cmds:
      - docker compose run --rm qbot bash

  compose-psql:
    cmds:
      - docker compose run --rm qbot task psql

  compose-fmt:
    cmds:
      - docker compose run --rm qbot task fmt

  compose-lint:
    cmds:
      - docker compose run --rm qbot task lint

  run:
    deps: [syntax-check, type-check]
    cmds:
      # - poetry run watchfiles 'python src/main.py run_polling' src
      - poetry run watchmedo auto-restart --patterns='*.py' --recursive -- poetry run python src/main.py run_polling

  tests:
    deps: [type-check]
    cmds:
      - poetry run pytest --ignore=src/tests/e2e --cov=src --cov-report html --cov-fail-under=96

  type-check:
    cmds:
      - poetry run mypy src

  syntax-check:
    cmds:
      - poetry run ruff check src --select=F --ignore=F401,F841

  test:
    deps: [syntax-check,type-check]
    cmds:
      - poetry run pytest {{.CLI_ARGS}}

  psql:
    cmds:
      - PGPASSWORD=admin psql -h postgres -U admin -d qbot

  fmt:
    cmds:
      - poetry run ruff check src --fix --fix-only

  lint:
    cmds:
      - poetry run ruff check src --output-format=concise
      - git ls-files | xargs ec
      - poetry run flake8 src
      - poetry run mypy src
      - poetry run sqlfluff lint migrations --dialect postgres

  clean:
    cmds:
      - git clean -f -d -x -e .env -e me.session -e .venv
      - docker rmi bot-qbot -f

  clear-cache:
    cmds:
      - redis-cli -h redis FLUSHALL

  migration:
    cmds:
      - poetry run yoyo new -m {{.CLI_ARGS}} --sql

  cspell-baseline:
    desc: "Generate cspell baseline"
    cmds:
      - git ls-files | grep -v -E 'src/tests/fixtures/' | xargs cspell --words-only | sort -uf > cspell_custom_words.txt
