"""Add Ayat.audio_id.

Revision ID: d6aa2e3f6fb1
Revises: a8fcbe4d7c8b
Create Date: 2022-08-15 19:04:11.233307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6aa2e3f6fb1'
down_revision = 'a8fcbe4d7c8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ayats', sa.Column('audio_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'ayats', 'files', ['audio_id'], ['file_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ayats', type_='foreignkey')
    op.drop_column('ayats', 'audio_id')
    # ### end Alembic commands ###
