"""Explose Podcast.

Revision ID: c2b3e293c2f7
Revises: b37656b99038
Create Date: 2022-08-25 14:50:00.843424

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c2b3e293c2f7'
down_revision = 'b37656b99038'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcasts', sa.Column('article_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcasts', 'article_link')
    # ### end Alembic commands ###
