"""Add File.link.

Revision ID: 922de1339010
Revises: 4bb4b4f8ed92
Create Date: 2022-08-23 17:22:31.799624

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '922de1339010'
down_revision = '4bb4b4f8ed92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'link')
    # ### end Alembic commands ###
