"""Add File.link.

Revision ID: e51b916361eb
Revises: 4bb4b4f8ed92
Create Date: 2022-08-24 15:03:09.568807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e51b916361eb'
down_revision = '4bb4b4f8ed92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'link')
    # ### end Alembic commands ###
