"""Create AdminMessage model.

Revision ID: d8b118750491
Revises: 12e29a627869
Create Date: 2022-08-16 16:57:57.386031

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd8b118750491'
down_revision = '12e29a627869'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'admin_messages',
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('text', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('key'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_messages')
    # ### end Alembic commands ###
