"""Add User.legacy_id

Revision ID: 72297b274c99
Revises: 8dce815ede2c
Create Date: 2022-08-14 23:09:23.963647

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '72297b274c99'
down_revision = '8dce815ede2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('legacy_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'legacy_id')
    # ### end Alembic commands ###
