"""init

Revision ID: f2265766d2e5
Revises: 
Create Date: 2022-08-14 18:15:50.187035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2265766d2e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suras',
    sa.Column('sura_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('sura_id')
    )
    op.create_table('ayats',
    sa.Column('ayat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('sura_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('ayat_number', sa.String(length=10), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('arab_text', sa.String(), nullable=True),
    sa.Column('transliteration', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sura_id'], ['suras.sura_id'], ),
    sa.PrimaryKeyConstraint('ayat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ayats')
    op.drop_table('suras')
    # ### end Alembic commands ###
