"""Initial migration.

Revision ID: 8dce815ede2c
Revises: 
Create Date: 2022-08-14 20:14:01.314961

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8dce815ede2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cities',
        sa.Column('city_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('city_id'),
    )
    op.create_table(
        'files',
        sa.Column('file_id', sa.String(), nullable=False),
        sa.Column('telegram_file_id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('file_id'),
    )
    op.create_table(
        'suras',
        sa.Column('sura_id', sa.Integer(), nullable=False),
        sa.Column('link', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('sura_id'),
    )
    op.create_table(
        'ayats',
        sa.Column('ayat_id', sa.Integer(), nullable=False),
        sa.Column('public_id', sa.String(), nullable=False),
        sa.Column('sura_id', sa.Integer(), nullable=False),
        sa.Column('day', sa.Integer(), nullable=True),
        sa.Column('ayat_number', sa.String(length=10), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('arab_text', sa.String(), nullable=False),
        sa.Column('transliteration', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['sura_id'],
            ['suras.sura_id'],
        ),
        sa.PrimaryKeyConstraint('ayat_id'),
    )
    op.create_table(
        'podcasts',
        sa.Column('podcast_id', sa.String(), nullable=False),
        sa.Column('file_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['file_id'],
            ['files.file_id'],
        ),
        sa.PrimaryKeyConstraint('podcast_id'),
    )
    op.create_table(
        'users',
        sa.Column('chat_id', sa.Integer(), nullable=False),
        sa.Column(
            'is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False
        ),
        sa.Column('comment', sa.String(), nullable=True),
        sa.Column('day', sa.Integer(), nullable=True),
        sa.Column('city_id', sa.String(), nullable=True),
        sa.Column('referrer_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['city_id'],
            ['cities.city_id'],
        ),
        sa.ForeignKeyConstraint(
            ['referrer_id'],
            ['users.chat_id'],
        ),
        sa.PrimaryKeyConstraint('chat_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('podcasts')
    op.drop_table('ayats')
    op.drop_table('suras')
    op.drop_table('files')
    op.drop_table('cities')
    # ### end Alembic commands ###
