"""Create FavoriteAyat model.

Revision ID: a8fcbe4d7c8b
Revises: 23858449989b
Create Date: 2022-08-15 18:43:47.261777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fcbe4d7c8b'
down_revision = '23858449989b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'favorite_ayats',
        sa.Column('ayat_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['ayat_id'],
            ['ayats.ayat_id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.chat_id'],
        ),
        sa.PrimaryKeyConstraint('ayat_id', 'user_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_ayats')
    # ### end Alembic commands ###
