# Generated by Django 5.0.6 on 2024-07-02 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512, unique=True)),
                ('has_webhook', models.BooleanField()),
                ('installation_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'gh_repos',
            },
        ),
        migrations.CreateModel(
            name='TouchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('date', models.DateField()),
                ('gh_repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ghrepo')),
            ],
            options={
                'db_table': 'touch_records',
            },
        ),
    ]
