# SPDX-FileCopyrightText: Copyright (c) 2018-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT

name: Test and release

on:
  # push:
  #   tags: "*"
  pull_request:
    branches: [ "master" ]

jobs:
  checks:
    env:
      TZ: "Europe/Moscow"
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:17.10
        env:
          POSTGRES_USER: almazilaletdinov
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:8
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
      rabbitmq:
        image: rabbitmq:3.13.7
        ports:
          - 5672:5672
          - 15672:15672
        env:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: pass
        options: --health-cmd "rabbitmqctl status" --health-interval 10s --health-timeout 5s --health-retries 5

    # uses: blablatdinov/tg-quranbot/.github/workflows/installing-dependencies.yml@master
    # uses: blablatdinov/tg-quranbot/.github/workflows/lint.yml@master

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'true'
    - name: Set up Python 3.14
      uses: actions/setup-python@v7
      with:
        python-version: "3.14.7"
    - name: Install Poetry
      uses: snok/install-poetry@v1.4.2
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v6
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root
    - name: create .env file
      run: echo '${{ secrets.E2E_ENV_SETUP }}' > .env
    - name: Create telethon session
      run: echo "${{ secrets.TELETHON_SESSION }}" | base64 --decode > me.session
    - name: Run e2e tests
      run: .venv/bin/pytest src/tests/e2e -vv

  build-and-push:
    # needs: checks
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get tag name
        id: tag_name
        # run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        run: echo "TAG_NAME=v3.8.8-a1" >> $GITHUB_OUTPUT
      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: blablatdinov/tg-quranbot:${{ steps.tag_name.outputs.TAG_NAME }}

  apply-migrations:
    needs: build-and-push
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14.7"
      - name: Install Dependencies
        run: |
          pip install yoyo-migrations==9.0.0 psycopg2-binary==2.9.9 setuptools==75.1.0
      - name: Apply migrations
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: |
          echo "[DEFAULT]
          sources = migrations
          database = \${POSTGRES_URL}
          batch_mode = on
          verbosity = 3" > yoyo.ini
          yoyo apply

  update-remote-container:
    needs: build-and-push
    runs-on: ubuntu-24.04
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Get tag name
        id: tag_name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Deploy with docker-compose on remote server
        run: |
          ssh www@${SERVER_IP} "${TAG_NAME}"

  change-pyproject-version:
    # needs: checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - run: |
          git fetch --tags --force && \
          latest=$(git tag --sort=creatordate | tail -1 | cut -c2-) && \
          sed -i '/^version = "/s/"[^"]*"/"'"$latest"'"/' pyproject.toml
      - uses: peter-evans/create-pull-request@v8
        with:
          branch: version-up
          commit-message: 'new version in pyproject.toml'
          delete-branch: true
          title: 'Up version in pyproject.toml'
          assignees: blablatdinov
          base: master
